Repository KelaiAffaf/githubCourse, pull requests merged in 2024-01, with the labels that each got.

#2 assia
  assia.html/assia.html
Labels: enhancement

#3 cc
  ghanou.html
Labels: documentation

#1 feature from Afaf
  afaf.html
Labels: bug
